# This is a GitHub workflow YAML file
# see https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
#
# If you want to update this file it's recommended to use a YAML validator
# https://marketplace.visualstudio.com/items?itemName=redhat.vscode-yaml
# configured to validate with https://json.schemastore.org/github-workflow.json
#
# For every push on a pull request, it
# - starts a machine on ubuntu
# - clone the git repository
# - install node, install npm deps
# - Executes report_performance_impact.mjs
# Read more in https://github.com/jsenv/performance-impact

name: performance_impact

on: pull_request_target

jobs:
  performance_impact:
    runs-on: ubuntu-20.04
    name: performance impact
    steps:
      - name: Setup git
        # "checkout@v3" documentation available at https://github.com/actions/checkout
        uses: actions/checkout@v3
      - name: Setup node ${{ matrix.node }}
        # "setup-node@v3" documentation available at https://github.com/actions/setup-node
        uses: actions/setup-node@v3
        with:
          node-version: "20.8.0"
      - name: Install node modules
        run: npm install
      - name: Report performance impact
        run: node --expose-gc ./.github/workflows/report_performance_impact.mjs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
